### ISSUE TITLE
bgpd module is missing

### ISSUE THREAD

**Issue by kkkiyoi** [yhchen-tsinghua/routing-anomaly-detection#1]
When I run (2 detect route change module), it shows no bgpd module after downloading the route change in RouteViews.

**Comment by yhchen-tsinghua** [comment]
Please see README [0. Prepare the environment](https://github.com/yhchen-tsinghua/routing-anomaly-detection?tab=readme-ov-file#0-prepare-the-environment) and make sure the BGPdump tool is properly set up.

```bash
git clone https://github.com/RIPE-NCC/bgpdump.git
cd bgpdump
sh ./bootstrap.sh
make
ln -s $(pwd)/bgpdump $YOUR_REPO_PATH/data/routeviews/bgpd
$YOUR_REPO_PATH/data/routeviews/bgpd -T # should print the test output
```

**Comment by yhchen-tsinghua** [comment]
I’m closing this issue for now. Feel free to reopen it if you have more related questions. Thanks for your input.
